### ISSUE TITLE
Cling requires dj_static

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#95]
Seems we introduced a dependency to `dj_static`. Unsure if this belongs in common or production requirements.

Gunicorn logs:
```
Traceback (most recent call last):
  File "/trix/developement/venv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/trix/developement/venv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/trix/developement/venv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/trix/developement/venv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/trix/developement/venv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/trix/developement/venv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/trix/developement/venv/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/trix/developement/venv/lib/python3.6/site-packages/trix/project/production/wsgi.py", line 2, in <module>
    from dj_static import Cling
ModuleNotFoundError: No module named 'dj_static'
```

**Comment by Elthan** [comment]
That's odd, but it's has always been there. For some reason I can't find the dependency though, I will add it.

**Comment by torgeirl** [comment]
Added in #96.
